development: &default
  adapter: postgresql
  encoding: unicode
  database: news_app_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: postgres
  port: 5432

test:
  <<: *default
  database: news_app_test

production:
  <<: *default
  encoding: utf8
  database: <%= ENV['PROD_DB_NAME'] %>
  username: <%= ENV['PROD_USERNAME'] %>
  password: <%= ENV['PROD_PASSWORD'] %>
  host: <%= ENV['PROD_HOSTNAME'] %>
  port: <%= ENV['PROD_PORT'] %>
